spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: 'jdbc:mysql://localhost:3306/solitafarm'
    username: adedamola
    password: adegboola
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: 'off'